### ISSUE TITLE
mycustom library and pubsubclient call back

### ISSUE THREAD

**Issue by vickeyhort** [knolleary/pubsubclient#115] opened 2016-01-23 19:04 UTC
Hi. I am trying to make my own library for my Esp8266 Arduino using ESP8266 library and PubSubClient library. Problem is pubsubclient call back function, It is giving error. May someone please help me? Here are ino, h, cpp and error log files.
[h.txt](https://github.com/knolleary/pubsubclient/files/101987/h.txt)
[ino.txt](https://github.com/knolleary/pubsubclient/files/101988/ino.txt)
[Error.txt](https://github.com/knolleary/pubsubclient/files/101989/Error.txt)
[cpp.txt](https://github.com/knolleary/pubsubclient/files/101990/cpp.txt)

**Comment by knolleary** [comment] 2016-01-23 20:15
Hi,

whilst I can recreate your error, my C++ knowledge is not good enough I know what the fix is.

The problem is this library expects the callback function signature to be:

    void (*callback)(char*,uint8_t*,unsigned int)

but you are providing a callback that is a member of a class:

    void EspMQTT::callback(char* topic, byte* payload, unsigned int length)

I don't know how to make those two match up in C++.

**Comment by tomkcook** [comment] 2016-01-26 09:56
@vickeyhort - see the repository tomkcook/pubsubclient for a version that can handle this.  You can set a callback from a class member function like this:

```
mqtt.set_callback([this] (char* topic, byte* payload, unsigned int length) { this->callback(topic, payload, length); }
```

**Comment by marvinroger** [comment] 2016-02-13 16:10
@tomkcook the @knolleary "version" can also handle this with the ESP8266, as the OP requested:

```c++
mqtt.setCallback(std::bind(&YourClass:_yourCallback, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
```

@vickeyhort, can you close this issue?

**Comment by vickeyhort** [comment] 2016-07-03 17:36
@tomkcook Sorry for such late reply, I was busy with one of my project. As you mentioned;
`mqtt.set_callback([this] (char* topic, byte* payload, unsigned int length) { this->callback(topic, payload, length); }`
Where should I use this piece of code? In my cpp file or ino file? I am really not understanding it.

**Closed** 2016-11-15 18:44 UTC

**Comment by jon-nfc** [comment] 2022-11-19 12:18
> @tomkcook the @knolleary "version" can also handle this with the ESP8266, as the OP requested:
> 
> ```c++
> mqtt.setCallback(std::bind(&YourClass:_yourCallback, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
> ```
> 
> @vickeyhort, can you close this issue?

@marvinroger, you ended a painful two hours of ~~banging my head on the keyboard~~ trying to come up with a solution to use a callback from an initialized class. You're a legend, cheers.

For any others that find this post, `pubsubclient.setcallback()` can be passed a callback method from an initialized class using the above.
