### ISSUE TITLE
 'yield' was not declared in this scope

### ISSUE THREAD

**Issue by mwolfaardt** [knolleary/pubsubclient#606] opened 2019-04-23 07:50 UTC
I'm receiving the following error : PubSubClient.cpp:225:12: error: 'yield' was not declared in this scope. I'm running Version 2.7.0.

**Comment by knolleary** [comment] 2019-04-23 09:06
Duplicate of #576 that you've already commented on. Please provide details - on the other issue - of what hardware you are trying to compile against.

**Closed by knolleary** 2019-04-23 09:06 UTC
