### ISSUE TITLE
Issue with MQTT publish within a pin interrupt (attachinterrupt) onn ESP8266

### ISSUE THREAD

**Issue by trneal** [knolleary/pubsubclient#118] opened 2016-01-26 00:52 UTC
It appears to be an issue with publishing an event within an pin (attachinterrupt) service routine on an ESP8266.  It appears to cause the ESP8266 to hang/reboot on pin state change (when interrupt is called).  Commenting out the MQTT publish from the interrupt routine eliminates the problem.  Similarly setting a flag in the interrupt routine to publish the MQTT event in the loop() works also.

**Comment by knolleary** [comment] 2016-01-26 07:04
Duplicate of #99

**Closed by knolleary** 2016-01-26 07:04 UTC
