### ISSUE TITLE
does not receive messages send during deep sleep

### ISSUE THREAD

**Issue by markus507** [knolleary/pubsubclient#232] opened 2017-01-11 20:29 UTC
Hello,

I'm using a NodeMCU with your libary. Due to power saving the NodeMCU goes to sleep for some time and then starts again.

My Problem is that Messages that were send during the sleep Phase are not recognized. I'm using the subscribe method with qos = 1:

`boolean result = mqtt.subscribe(tempChar, 1);`

My Broker is mosquitto. 

What do I Need to do to get the message received after powering up again? Perhaps you have some example Code?

Thank you
Markus

**Comment by knolleary** [comment] 2017-01-11 20:30
The library only supports clean-session connections.

Duplicate of https://github.com/knolleary/pubsubclient/issues/200 so closing this one.

**Closed by knolleary** 2017-01-11 20:30 UTC
