### ISSUE TITLE
When the "clean session = off" working?

### ISSUE THREAD

**Issue by r666t** [knolleary/pubsubclient#126] opened 2016-02-10 10:14 UTC
Please, for several projects is very important that we can recover the messages that the server sent while the esp was turn off.

Can we use "clean session off" with the actual library or we 'll have wait?

Thanks for your hard work!!!

**Comment by knolleary** [comment] 2016-02-10 11:24
Hi, this is a duplicate of #86 which you've already commented on.

I can certainly see the use of non clean sessions for subscribing clients. The problem is the expectation this brings for publishing clients; we have no way to store state in the client, so if we add qos1/2 publishes, their flows will be left incomplete over a reconnect.

So whilst I'm not against adding support for this, please understand there are wider side effects you may not be concerned by, but that I will have to deal with.

**Closed by knolleary** 2016-02-10 11:24 UTC
